### ISSUE TITLE
Piglin Bartering Pack Books

### ISSUE THREAD

**Issue by Katables** [PurpurMC/PurpurPacks#12]
We're running the **Rebalanced Piglin Bartering [PurpurPack]** V3.0 & recently updated V3.1 (both having the same issue).

Problem:  Running the Books in the Loot table gives ALL enchanted books.
          _"type": "minecraft:item",
          "name": "minecraft:book",
          "weight": 5,
          "functions": [
            {
              "function": "minecraft:enchant_randomly",
              "enchantments": [
                "minecraft:soul_speed"_
                
                
Expected behavior: Bartering should only give Soul Speed Books 1-3.

Solution for now: Deleted Books from the loot table.

**Comment by RhythmicSys** [comment]
Fix has been pushed, and should be available now:
https://modrinth.com/datapack/purpurpacks-rebalanced-piglin-bartering/version/3.2
Thanks for reporting!

**Comment by Katables** [comment]
Hey @RhythmicSys sorry to necro this post. But it seems that the Enchanted books are still happening?
It seems like the Enchanted Books are mentioned twice? I think something funny is happening lol

![Image](https://github.com/user-attachments/assets/df949a16-32ed-4a75-9fd9-0007abcdb604)

**Line 7-16**
 {
          "type": "minecraft:item",
          "name": "minecraft:enchanted_book",
          "functions": [
            {
              "function": "minecraft:set_enchantments",
              "enchantments": {}
            }
          ]
        },

**Line 249-257**
       {
          "type": "minecraft:item",
          "name": "minecraft:book",
          "weight": 5,
          "functions": [
            {
              "function": "minecraft:enchant_randomly",
              "options": "minecraft:soul_speed"
            }

**Comment by RhythmicSys** [comment]
Strange. I think I might just need to change the format of this altogether

**Comment by RhythmicSys** [comment]
For now I've pushed a version that just takes out the enchanted book, but I definitely need to redo this, as there's a number of things that don't make sense (Piglins giving the player gold blocks, for instance)

**Comment by Katables** [comment]
Any update on this :D?

**Comment by RhythmicSys** [comment]
Does the new version not fix the issue?

**Comment by Katables** [comment]
Well ideally we still want SoulSpeed, the newer version removed all books right? Or did I misread.

**Comment by Katables** [comment]
Oh omg lol okay I'll give it a try in a bit ❤️
